// ignore_for_file: constant_identifier_names, unnecessary_const

import 'models/category.dart';
import 'models/trip.dart';

const Category_data = [
  Category(id: 'c1', title: 'Lakes', imageUrl: 'images/categories/1.png'),
  Category(id: 'c2', title: 'Beaches', imageUrl: 'images/categories/2.png'),
  Category(id: 'c3', title: 'Mountains', imageUrl: 'images/categories/3.png'),
  Category(id: 'c4', title: 'Castles', imageUrl: 'images/categories/4.png'),
  Category(id: 'c5', title: 'Parks', imageUrl: 'images/categories/5.png'),
  Category(
    id: 'c6',
    title: 'Shopping Malls',
    imageUrl: 'images/categories/6.png',
  ),
  Category(id: 'c7', title: 'Old Bazaars', imageUrl: 'images/categories/7.png'),
];
const Trip_data = const [
  Trip(
    id: 't1',
    categories: ['c1'],
    title: 'Al-Thawra leak',
    tripType: TripType.Nature,
    imageUrl: 'images/trips/lakethawra.jpg',
    properities: [
      'Swimming',
      'Fishing',
      'Family picnics',
      'BBQ',
      'Sunset views',
      'Nature vibes',
    ],
    isInSummer: true,
    isInWinter: true,
    governorate: Governorate.Raqqa,
    description:
        "Al-Thawra Lake, formerly known as Al-Assad Lake, is Syria's largest artificial lake, formed by the Euphrates Dam. After liberation, the lake was renamed to 'Al-Thawra' (meaning 'The Revolution'). Surrounded by gentle hills and peaceful views, it`s known for its fresh water, relaxing atmosphere, and beautiful sunsets. Whether you want to swim, fish, have a family picnic, or just vibe in nature, Al-Thawra Lake is the spot to be.",
  ),
  Trip(
    id: 't2',
    categories: ['c1', 'c5'],
    title: 'Mashqita',
    imageUrl: 'images/trips/Mashqita.jpg',
    isInSummer: true,
    isInWinter: false,
    properities: [
      'Boating',
      'Kayaking',
      'Picnics',
      'Mountain breeze',
      'Nature views',
      'Chill vibes',
    ],
    tripType: TripType.Adventure,
    governorate: Governorate.Latakia,
    description:
        "Mashqita Lake is a hidden gem nestled in the lush green hills of Syria’s Latakia region. Surrounded by forests and rolling mountains, the lake is famous for its crystal clear water and peaceful, natural vibes. It’s the perfect place for boat rides, kayaking, picnics, and nature walks. Whether you’re after adventure or just want to chill and enjoy stunning views, Mashqita Lake delivers big time.",
  ),
  Trip(
    id: 't3',
    categories: ['c1'],
    title: 'Yarmouk',
    imageUrl: 'images/trips/Yarmouk.jpg',
    isInSummer: true,
    isInWinter: false,
    properities: [
      'Hiking',
      'Camping',
      'History',
      'River views',
      'Birdwatching',
      'Exploration',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Daraa,
    description:
        "Welcome to the Yarmouk Dam, one of Syria`s most important water reservoirs! Built on the famous Yarmouk River, this dam is a lifeline for the region, providing water for irrigation, farming, and nearby communities. The area is surrounded by scenic valleys and dramatic landscapes, making it a great spot for hiking, birdwatching, and exploring ancient ruins from different eras. The dam itself is an impressive structure, and the surrounding nature is perfect for adventure seekers and anyone wanting to escape the city for a day. Don’t forget your camera—sunsets here are next level!",
  ),
  Trip(
    id: 't4',
    categories: ['c1'],
    title: 'Lake Blouran',
    imageUrl: 'images/trips/Blouran.png',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Hiking',
      'Trailblazing',
      'Nature discovery',
      'Photography',
      'Rock exploring',
      'Secret spots',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Latakia,
    description:
        "Balloran Lake is a mountain gem surrounded by forests and wild nature. It’s perfect for hiking, exploring secret spots, and just soaking up the chill mountain vibes. Grab your friends and discover why locals call this place a true escape!",
  ),

  Trip(
    id: 't5',
    categories: ['c1'],
    title: 'Wahda Dam',
    imageUrl: 'images/trips/Alwahda.jpg',
    isInSummer: true,
    isInWinter: false,
    properities: [
      'Nature walks',
      'Birdwatching',
      'Picnic exploring',
      'Wildlife spotting',
      'Hidden trails',
      'Photography',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Daraa,
    description:
        "Wahda Dam (Unity Dam) sits on the Yarmouk River, linking Syria and Jordan with a massive reservoir and awesome views. It’s perfect for nature walks, birdwatching, and chilling by the water. A must-visit for anyone craving a mix of history, nature, and fresh air!",
  ),
  Trip(
    id: 't6',
    categories: ['c2', 'c5'],
    title: 'Ras AL-Basit',
    imageUrl: 'images/trips/albasit.png',
    isInSummer: true,
    isInWinter: false,
    properities: [
      'Black sand',
      'Turquoise water',
      'Ancient ruins',
      'Pine forests',
      'Seafood',
      'Sunsets',
      'Family-friendly',
      'Water sports',
      'Nature walks',
    ],

    tripType: TripType.Chill,
    governorate: Governorate.Latakia,
    description:
        "Ras al-Basit is a unique coastal destination on Syria`s Mediterranean shore, just north of Latakia. Not only is it famous for its dramatic black sand beaches and clear blue water, but this area is also rich in history. In ancient times, Ras al-Basit was known as Posidium and served as an important port for the Greeks, Romans, and later civilizations. Archaeological remains from these eras can still be seen near the beach, giving visitors a direct connection to the region’s past. Today, Ras al-Basit is loved for its peaceful natural setting, perfect for swimming, family trips, and discovering the stories hidden in its sand and ruins. Whether you`re a nature lover or a history buff, this beautiful spot on the Mediterranean Sea offers something for everyone.",
  ),
  Trip(
    id: 't7',
    categories: ['c2', 'c5'],
    title: 'Wadi Qandil',
    imageUrl: 'images/trips/qandil.jpg',
    isInSummer: true,
    isInWinter: false,
    description:
        "Wadi Qandil Coast is one of the hidden gems of Latakia’s shoreline, set right on the Mediterranean Sea. Known for its crystal clear water, soft sandy beach, and the shade of pine and eucalyptus trees, this spot is perfect for anyone looking to relax away from the crowds. Wadi Qandil is family-friendly, with shallow areas for kids, plenty of space for picnics or camping, and local seafood restaurants just a short walk away. Whether you’re in the mood for swimming, sunbathing, or just chilling under the trees, Wadi Qandil Coast offers pure summer vibes and stunning views from sunrise to sunset.",
    tripType: TripType.Chill,
    governorate: Governorate.Latakia,
    properities: [
      'Clear water',
      'Sandy beach',
      'Pine trees',
      'Quiet vibes',
      'Picnics',
      'Camping',
      'Seafood',
      'Family-friendly',
      'Relaxation',
      'Beautiful views',
    ],
  ),
  Trip(
    id: 't8',
    categories: ['c2'],
    title: 'Arwad Island',
    imageUrl: 'images/trips/Arwad.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Historic island',
      'Phoenician ruins',
      'Stone alleys',
      'Seafood',
      'Boat rides',
      'Harbor views',
      'Handicrafts',
      'No cars',
      'Crusader castle',
      'Chill vibes',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Tartus,
    description:
        "Arwad Island is Syria`s only inhabited island, floating just off the coast of Tartus in the Mediterranean Sea. Known for its fascinating Phoenician and Crusader history, Arwad charms visitors with narrow stone alleys, ancient fortresses, and a relaxed fishing village atmosphere. The island is completely car-free, so you`ll explore by foot, discovering local crafts, historic sites, and cozy seafood restaurants along the way. Reached by a quick boat ride from Tartus, Arwad is perfect for anyone who loves history, sea views, and a peaceful escape from the city. Don`t miss the stunning sunset over the harbor!",
  ),
  Trip(
    id: 't9',
    categories: ['c3'],
    title: 'Al-zawyeh',
    imageUrl: 'images/trips/Zawyeh.png',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Dead Cities',
      'Byzantine ruins',
      'Old churches',
      'Mountain views',
      'Hiking',
      'Ancient villages',
      'Archaeological sites',
      'Olive groves',
    ],
    tripType: TripType.Adventure,
    governorate: Governorate.Idlib,
    description:
        "Jabal al-Zawiya is a historic mountain region in the southern countryside of Idlib, famous for its dramatic landscapes, ancient villages, and deep-rooted history. This area was home to many of Syria`s famous 'Dead Cities'—abandoned Byzantine towns and early Christian churches dating back to the 4th-6th centuries AD. The ruins of Serjilla and al-Bara are must-see highlights, with their stone houses, tombs, and ancient olive presses still standing after centuries. Over the ages, Jabal al-Zawiya has witnessed everything from Roman trade routes to medieval fortress building, making it a living museum for travelers, hikers, and history buffs alike.",
  ),
  Trip(
    id: 't10',
    categories: ['c3'],
    title: 'Mount Qasioun',
    imageUrl: 'images/trips/qasyoun.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'City views',
      'Sunsets',
      'Legends',
      'Cafés',
      'Photography',
      'Mountain air',
      'History',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Damascus,
    description:
        "Mount Qasioun rises above Damascus as both a natural wonder and a historic landmark. For centuries, this mountain has been the city`s silent guardian, offering panoramic views over Syria`s capital—especially magical at sunset or when Damascus lights up at night. Qasioun is steeped in legend: local tradition says it`s the site where Cain and Abel`s story unfolded, and where ancient prophets once prayed. Today, visitors come for the stunning scenery, mountain air, and the chance to experience Damascus from above. Cafés and viewpoints along the mountain make it a favorite spot for families, friends, and travelers looking for a unique perspective on one of the world`s oldest cities.",
  ),

  Trip(
    id: 't11',
    categories: ['c3'],
    title: 'Mount Hermon',
    imageUrl: 'images/trips/Alshekh.jpg',
    isInSummer: true,
    isInWinter: false,
    properities: [
      'Snowy peak',
      'Highest point',
      'Epic views',
      'Cool climate',
      'Hiking',
      'Legends',
      'Wildflowers',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Rif_Dimashq,
    description:
        "Mount Hermon, known locally as Jabal al-Sheikh, is Syria`s highest peak, towering over the border with Lebanon and Palestine. This legendary mountain is famous for its snow-capped summit, cool climate, and breathtaking views that stretch across the region. In winter, Jabal al-Sheikh turns into a magical landscape, attracting visitors with its rare Syrian snow and unique alpine scenery. The mountain holds a special place in local culture and folklore, and its slopes are dotted with wildflowers, forests, and ancient ruins. Whether you`re into hiking, photography, or just want to experience Syria`s nature at its finest, Mount Hermon is an unforgettable destination for explorers and adventure lovers.",
  ),

  Trip(
    id: 't12',
    categories: ['c4'],
    title: 'Citadel of Aleppo',
    imageUrl: 'images/trips/Aleppo.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Ancient fortress',
      'City views',
      'Historic mosques',
      'Stone walls',
      'UNESCO site',
      'Underground passages',
      'Iconic landmark',
    ],
    tripType: TripType.History,
    governorate: Governorate.Aleppo,
    description:
        "Aleppo Citadel stands at the heart of the city, rising majestically above the ancient streets of Aleppo. This legendary fortress is one of the oldest and largest in the world, with roots stretching back to at least the 3rd millennium BC. Over the centuries, it has witnessed the rule of Hittites, Greeks, Romans, Byzantines, Ayyubids, and Ottomans—each leaving their mark on its walls. Visitors can explore grand gates, towering walls, mosques, royal halls, underground passages, and centuries-old ruins. The citadel offers not only a journey through history, but also breathtaking views over the city. A visit to Aleppo isn`t complete without standing atop this mighty landmark and soaking in the stories it holds.",
  ),

  Trip(
    id: 't13',
    categories: ['c4'],
    title: 'Krak des Chevaliers',
    imageUrl: 'images/trips/Krak.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Crusader fortress',
      'UNESCO site',
      'Massive towers',
      'Secret tunnels',
      'Countryside views',
      'Historic chapel',
      'Legendary landmark',
    ],
    tripType: TripType.History,
    governorate: Governorate.Homs,
    description:
        "Krak des Chevaliers, also known as Qalaat al-Hosn, is one of the world`s greatest medieval castles and a UNESCO World Heritage Site. Perched atop a hill in western Syria, this fortress was built by Crusader knights in the 12th century and later expanded by the Mamluks. Its massive stone walls, towers, drawbridges, and hidden passages have witnessed centuries of epic battles and dramatic history. Today, visitors can wander through grand halls, explore the ancient chapel, and climb the ramparts for breathtaking views over the surrounding countryside. Krak des Chevaliers is not just an architectural marvel—it`s a symbol of Syria`s rich past and a must-see for history lovers and adventurers alike.",
  ),

  Trip(
    id: 't14',
    categories: ['c4'],
    title: 'Qalʿat al-Marqab',
    imageUrl: 'images/trips/Marqab.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Basalt walls',
      '14 towers',
      'Cisterns',
      'Chapel',
      '360 m hilltop',
      'Medieval layers',
      'Crusader stronghold',
      'Mamluk siege 1285',
      'Panoramic views',
      'Under restoration',
    ],
    tripType: TripType.History,
    governorate: Governorate.Tartus,
    description:
        "Perched on a volcanic hill just southeast of Baniyas in Tartous Governorate, Qalʿat al‑Marqab (Margat Castle) is one of the largest and most impressive Crusader fortresses in Syria. Founded in 1062 during the early Islamic era, it became a major stronghold for the Knights Hospitaller after 1186. The fortress boasts thick basalt walls, 14 defensive towers, underground cisterns, a chapel, and spacious courtyards. Over centuries it resisted Saladin, held out against crusader attacks, but finally fell to Mamluk Sultan Qalawun in 1285 after a lengthy siege. With panoramic views of the Mediterranean and rugged mountains, Marqab Castle is a must-visit for history lovers and photographers who want to wander through Byzantine, Crusader, and Mamluk layers of history.",
  ),

  Trip(
    id: 't15',
    categories: ['c4'],
    title: 'Citadel of Saladin',
    imageUrl: 'images/trips/Saladin.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'UNESCO World Heritage Site',
      'Located in Latakia Governorate',
      'Captured by Saladin in 1188',
      'Massive rock-cut moat',
      'Byzantine, Crusader, and Islamic architecture',
      'Impressive defensive towers and walls',
      'Ancient chapel and cisterns',
      'Panoramic mountain and forest views',
      'Winding stone paths and secret chambers',
      'Perfect for history and nature lovers',
    ],
    tripType: TripType.History,
    governorate: Governorate.Latakia,
    description:
        "The Citadel of Salah Ed-Din, also called Saladin`s Castle, is one of the most impressive medieval fortresses in Syria. Rising above pine-covered hills in Latakia Governorate, the citadel is famous for its massive rock-cut moat and unbeatable defenses. Originally built by the Byzantines, it was expanded by Crusaders and later captured by the legendary Sultan Saladin in 1188. Visitors can explore ancient chapels, stone towers, hidden chambers, and winding paths, all while enjoying breathtaking mountain and forest views. With its unique blend of Byzantine, Crusader, and Islamic architecture, this UNESCO World Heritage Site is a must-see for anyone who loves history, adventure, or stunning landscapes.",
  ),
  Trip(
    id: 't16',
    categories: ['c5'],
    title: 'Norias Park',
    imageUrl: 'images/trips/Norias Park.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Seventeen historic wooden norias along the Orontes',
      'Some wheels reach nearly 20 m diameter',
      'Medieval Ayyubid, Mamluk & Ottoman engineering',
      'Gentle creaking sound as wheels turn—“song of the norias”',
      'Stone aqueducts once fed gardens & city fountains',
      'Located in a peaceful riverside garden park',
      'Riverside cafés and shaded seating areas',
      'Ideal for strolls, picnics & photography',
      'Iconic symbol of Hama’s cultural heritage',
      'UNESCO Tentative Heritage Site',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Hama,
    description:
        "Norias Park in Hama is a tranquil riverside green space on the banks of the Orontes River, famous for its medieval wooden water wheels known as norias. These towering wheels—some reaching up to 20 meters in diameter—used to lift water centuries ago for irrigation and urban use. Today, 17 beautifully preserved norias still turn quietly, making a mesmerizing creaking sound as they scoop water into stone aqueducts. Surrounded by lush gardens, shaded pathways, riverside cafés, and historic charm, Norias Park is a perfect spot for relaxation, photography, and connecting with Syria`s remarkable past.",
  ),
  Trip(
    id: 't17',
    categories: ['c5'],
    title: 'Tishreen Park',
    imageUrl: 'images/trips/tishreen.jpg',
    isInSummer: true,
    isInWinter: false,
    properities: [
      'Large green space',
      'Flower gardens',
      'Fountains',
      'Playgrounds',
      'Cafés',
      'Family-friendly',
      'Events & festivals',
      'Jogging paths',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Damascus,
    description:
        "Tishreen Park is the largest public park in Damascus and one of the city`s most popular green spaces. Located near Umayyad Square, the park features wide open lawns, tree-lined pathways, colorful flowerbeds, and beautiful fountains. It`s a favorite spot for families, joggers, and anyone looking to relax away from the city noise. Tishreen Park hosts major events and festivals—most famously, the annual Damascus Flower Show—which brings the gardens to life with music, art, and stunning floral displays. With playgrounds, cafés, and peaceful picnic areas, the park offers a breath of fresh air in the heart of Syria`s capital.",
  ),
  Trip(
    id: 't18',
    categories: ['c5'],
    title: 'Al-Jahiz',
    imageUrl: 'images/trips/aljahiz.jpg',
    isInSummer: true,
    isInWinter: false,
    properities: [
      'Bronze statue of Al-Jahiz',
      'Green lawns',
      'Water features',
      'Playground',
      'Cafés nearby',
      'Quiet city escape',
      'Family-friendly',
    ],
    tripType: TripType.Nature,
    governorate: Governorate.Damascus,
    description:
        "al-Jahiz  park is a charming urban oasis tucked behind the  Library in the Maliki district of central Damascus. Named after the famous Arab polymath Al-Jahiz, the park honors his legacy with a bronze statue that celebrates his contributions to science, literature, and philosophy. Its well-manicured lawns, shady trees, ornamental water features, and winding paths make it a peaceful escape from the city bustle. With kids` playgrounds, benches, and nearby cafés and restaurants, Hadiqat al-Jahiz is popular with families, students, and locals seeking greenery and calm in the heart of the Old City.",
  ),
  Trip(
    id: 't19',
    categories: ['c6'],
    title: 'Town Center Mall',
    imageUrl: 'images/trips/TownCenterMall.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Modern multi-level shopping complex',
      'Wide selection of local and international brands',
      'Trendy fashion stores and boutiques',
      'Large supermarket and convenience shops',
      'Food court with global cuisine options',
      'Cafés, dessert spots, and coffee shops',
      'Cinema and entertainment center',
      'Kids’ play area and arcade',
      'ATM, banking, and essential services',
      'Secure parking and easy access location',
      'Popular spot for families and youth',
      'Regular events and seasonal sales',
      'Free Wi-Fi throughout the mall',
    ],
    tripType: TripType.Chill,
    governorate: Governorate.Damascus,
    description:
        "Town Center Mall is one of Damascus’s top shopping and entertainment destinations. Spread over multiple levels, the mall offers a wide mix of local and international brand stores, trendy fashion boutiques, and a large supermarket. Whether you’re in the mood for shopping, catching a movie, or just grabbing coffee with friends, Town Center has you covered. The food court features global eats, from fast food to sweet treats, and there are plenty of cafés to chill in. With a cinema, kids’ play area, free Wi-Fi, and regular events, it’s the perfect spot for families, youth, and anyone looking for fun and convenience in the heart of the city.",
  ),

  Trip(
    id: 't20',
    categories: ['c6'],
    title: 'Damascino Mall ',
    imageUrl: 'images/trips/DamascinoMall.jpg',
    isInSummer: false,
    isInWinter: false,
    properities: [
      'Modern multi-story mall in central Damascus',
      'Diverse range of brand-name shops',
      'Fashion boutiques and accessory stores',
      'Large electronics and tech outlets',
      'Variety of restaurants and food spots',
      'Popular dessert cafés and coffeehouses',
      'Supermarket for everyday essentials',
      'Spacious indoor play area for kids',
      'Arcade and entertainment zone',
      'Regular deals and seasonal sales',
      'Secure parking facilities',
      'Convenient location with easy access',
      'Family-friendly environment',
      'Events and special promotions year-round',
    ],
    tripType: TripType.Chill,
    governorate: Governorate.Damascus,
    description:
        "Damascino Mall is a modern shopping hub in the heart of Damascus, known for its wide selection of brand-name stores, fashion boutiques, and electronics outlets. The mall’s inviting atmosphere makes it a favorite spot for both families and young people to shop, dine, and hang out. You’ll find everything from trendy clothing and accessories to tasty eats in the diverse food court, plus dessert cafés and cozy coffee shops. Damascino Mall also features a large kids’ play area and arcade, making it easy to keep the whole crew entertained. With regular events, easy parking, and a prime city location, it’s your go-to spot for shopping and good vibes in Damascus.",
  ),
  Trip(
    id: 't21',
    categories: ['c6'],
    title: 'Sham City Center Mall',
    imageUrl: 'images/trips/Shamcitycentermall.jpg',
    isInSummer: false,
    isInWinter: false,
    properities: [
      'Spacious, multi-level shopping mall',
      'Mix of local and international brand stores',
      'Trendy clothing and fashion boutiques',
      'Home appliances and electronics outlets',
      'Large supermarket and convenience shops',
      'Food court with diverse dining options',
      'Cafés, dessert shops, and chill zones',
      'Modern cinema and entertainment center',
      'Kids’ play area and game arcade',
      'Banking and essential services on site',
      'Free Wi-Fi and comfy seating areas',
      'Secure parking and easy access',
      'Popular for families, students, and tourists',
      'Regular sales events and activities',
    ],
    tripType: TripType.Chill,
    governorate: Governorate.Damascus,
    description:
        "Sham City Center Mall is one of Damascus’s go-to spots for shopping, food, and fun. With its spacious modern layout, the mall brings together top local and international brands, stylish boutiques, and a big supermarket for all your essentials. Grab a bite at the food court, chill in one of the many cafés, or catch the latest movie at the cinema. There’s a dedicated kids’ area and arcade to keep little ones entertained, plus plenty of seating and free Wi-Fi to relax. With secure parking and a lively, family-friendly vibe, Sham City Center is the perfect hangout for shoppers, students, and anyone looking for a good time in the city.",
  ),
  Trip(
    id: 't22',
    categories: ['c7'],
    title: 'Al-Hamidiyah',
    imageUrl: 'images/trips/AlHamidiyah.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Largest souq in Damascus',
      'Historic covered market with Roman origins',
      'Famous for textiles, clothes, and fabrics',
      'Traditional sweets (Bakdash ice cream!)',
      'Perfumes, gold, and jewelry shops',
      'Souvenirs and handicrafts',
      'Leads straight to the Umayyad Mosque',
      'Bustling, vibrant atmosphere',
      'Rows of cafés and snack shops',
      'Open daily, central Old Damascus',
    ],
    tripType: TripType.Adventure,
    governorate: Governorate.Damascus,
    description:
        "Al-Hamidiyah Souq is the largest and most famous bazaar in Damascus. This covered market stretches from the Roman columns near the Citadel all the way to the Umayyad Mosque, buzzing with energy, colors, and the scent of spices and perfumes. With its high arched ceiling and endless rows of shops, it’s the go-to spot for everything from textiles and clothing to sweets, souvenirs, jewelry, and traditional crafts. Grab some legendary Bakdash ice cream and get lost in centuries of history!",
  ),
  Trip(
    id: 't33',
    categories: ['c7'],
    title: 'Al-Buzuriyah ',
    imageUrl: 'images/trips/AlBuzuriyah.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Historic spice market',
      'Famous for spices, herbs, and dried fruits',
      'Aleppo soap and traditional sweets',
      'Vibrant colors and strong aromas',
      'Located near Umayyad Mosque',
      'Old-world market vibes',
      'Popular with locals and visitors',
      'Packed with food stalls and herbal shops',
      'Great for souvenirs and gifts',
      'Part of Damascus Old City',
    ],
    tripType: TripType.Adventure,
    governorate: Governorate.Damascus,
    description:
        "Al-Buzuriyah Souq is Damascus’s legendary spice market, tucked between historic alleys near the Umayyad Mosque. The air here is thick with the aromas of spices, dried fruit, nuts, and centuries-old recipes. Colorful stalls overflow with local sweets, herbal teas, and handmade Aleppo soap. It’s a must-visit for foodies, chefs, and anyone wanting a true sensory experience of Syrian culture.",
  ),
  Trip(
    id: 't34',
    categories: ['c7'],
    title: 'Al-Madina',
    imageUrl: 'images/trips/AlMadina.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'One of the world’s largest covered markets',
      'Over 13 km of alleyways',
      'Roots in medieval era',
      'Famous for textiles, silk, and jewelry',
      'Spices, soap, crafts, and antiques',
      'Historic stone arches and architecture',
      'Bustling, authentic atmosphere',
      'Cafés and tea shops hidden inside',
      'Central to Aleppo Old City',
      'UNESCO World Heritage Site area',
    ],
    tripType: TripType.Chill,
    governorate: Governorate.Aleppo,
    description:
        "Souq Al-Madina in Aleppo is one of the oldest and largest covered markets in the world. Stretching over 13 kilometers of maze-like alleys, the bazaar dates back to medieval times and has been a commercial heart of the city for centuries. Here, you’ll find everything: silk, textiles, jewelry, spices, soap, and local crafts. The market’s ancient stone arches and lively trading scenes make it an unforgettable experience for travelers and history lovers alike.",
  ),
  Trip(
    id: 't35',
    categories: ['c7'],
    title: 'Al-Attarin',
    imageUrl: 'images/trips',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Traditional spice and apothecary market',
      'Aromatic blends of spices and herbs',
      'Essential oils and traditional medicine',
      'Colorful, sensory-packed atmosphere',
      'Located in Old Damascus and Old Aleppo',
      'Popular for unique gifts and remedies',
      'Historic market setting',
      'Family-run stalls with old recipes',
      'Great for teas and dried flowers',
      'Cultural hotspot for locals and tourists',
    ],
    tripType: TripType.Adventure,
    governorate: Governorate.Aleppo,
    description:
        "Souq Al-Attarin, or the Spice Dealers’ Market, is a historic bazaar found in both Damascus and Aleppo, famous for its aromatic shops selling spices, traditional medicines, oils, and dried flowers. Walk through the narrow alleys and you’ll be hit by the incredible blend of scents and vibrant displays. It’s a classic spot for those seeking the flavors and healing traditions of the Middle East.",
  ),
  Trip(
    id: 't36',
    categories: ['c7'],
    title: 'Al-Attarin',
    imageUrl: 'images/trips/AlAttarin.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Traditional spice and apothecary market',
      'Aromatic blends of spices and herbs',
      'Essential oils and traditional medicine',
      'Colorful, sensory-packed atmosphere',
      'Located in Old Damascus and Old Aleppo',
      'Popular for unique gifts and remedies',
      'Historic market setting',
      'Family-run stalls with old recipes',
      'Great for teas and dried flowers',
      'Cultural hotspot for locals and tourists',
    ],
    tripType: TripType.Adventure,
    governorate: Governorate.Aleppo,
    description:
        "Souq Al-Attarin, or the Spice Dealers’ Market, is a historic bazaar found in both Damascus and Aleppo, famous for its aromatic shops selling spices, traditional medicines, oils, and dried flowers. Walk through the narrow alleys and you’ll be hit by the incredible blend of scents and vibrant displays. It’s a classic spot for those seeking the flavors and healing traditions of the Middle East.",
  ),
  Trip(
    id: 't36',
    categories: ['c7'],
    title: 'Al-Khayyatin',
    imageUrl: 'images/trips/AlKhayyatin.jpg',
    isInSummer: true,
    isInWinter: true,
    properities: [
      'Historic tailors’ market',
      'Handmade clothing and textiles',
      'Skilled local craftsmen',
      'Classic Syrian styles and attire',
      'Cozy, intimate bazaar vibe',
      'Located in central Hama',
      'Family-owned shops',
      'Old-school sewing machines',
      'Unique, authentic atmosphere',
      'Great for custom clothing and fabrics',
    ],
    tripType: TripType.Adventure,
    governorate: Governorate.Hama,
    description:
        "Souq Al-Khayyatin in Hama is a historic tailors’ market, where generations of skilled craftsmen have cut, sewn, and sold traditional clothing and textiles. It’s a small, cozy bazaar lined with shops selling handmade garments, local fabrics, and classic Syrian attire. The air is filled with the sound of sewing machines and the scent of fresh cotton—an authentic slice of Syria’s craft heritage.",
  ),
];
